### root domain test
GET http://localhost:8000

##### ADMIN API ######
### get admin api
GET http://localhost:8000/api/v1/admin/

### post admin api
POST http://localhost:8000/api/v1/admin/
Content-Type: application/json

{
    "fName":"admin",
    "lName":"admin",
    "email":"abcd@gmail.com",
    "phone":"1234567890",
    "address":"Sydney",
    "dob":"1990-08-21",
    "password":"Admin"
}

### post admin email verification api
POST http://localhost:8000/api/v1/admin/email-verification
Content-Type: application/json

{
    "email":"abcd@gmail.com",
  "emailValidationCode":"4f12d581-3f38-4a18-ba29-4e1e9a1e698anpm "
}

### patch admin api
PATCH http://localhost:8000/api/v1/admin/

### Login admin API
POST http://localhost:8000/api/v1/admin/login
Content-Type: application/json

{
    "email":"sam1@smith.com",
 "password":"123456"
}


###==========CATEGORY SECTION =============#####
POST http://localhost:8000/api/v1/category
Content-Type: application/json

{
  "parentCatId" : "62a7d59960b99f7b6da2482d",
  "catName":"Cricket Ball"
}

### get all active categories
GET http://localhost:8000/api/v1/category

### update status of categories

PATCH http://localhost:8000/api/v1/category
Content-Type: application/json

{
  "_id": "62a7d67a3b89c5ed5290ae68",
  "status": "active"
}

### post product
POST http://localhost:8000/api/v1/products
Content-Type:application/json

{
  
    "name":"MacBook Pro Inch",
    "sku":"MBP-114",
    "description":"asdfas dsda f sdf sd f sdf  fa fdsf  sdf dsf ",
    "qty":100,
    "price":3000,axios
    "salesPrice":0,
    "salesDate":null
    
}

### get all products
GET http://localhost:8000/api/v1/products

### get single product
GET http://localhost:8000/api/v1/products/62b0f99c66b6b43fee23971c

### Update product
PUT http://localhost:8000/api/v1/products
Content-Type:application/json

{
  
    "name":"MacBook asdasd adsasdas Pro Inch",
    "catId":null,
    "description":"asdfas dsda f sdf sd f sdf  fa fdsf  sdf dsf ",
    "qty":100,
    "price":3000,
    "salesStartDate":null,
    "salesEndDate":null,
    "salesPrice":0,
    "status":"inactive"
}


#-------------Payment Method API----------------#

### get payment method
GET http://localhost:8000/api/v1/payment-method

### post payment method
POST http://localhost:8000/api/v1/payment-method
Content-Type:application/json

{
  "name": "Pay BY Credit Card",
  "status":"active",
  "description":"Use this payment method to pay by Credit or Debit masterCard"
}

### delete payment method
DELETE  http://localhost:8000/api/v1/payment-method/asdsds

### post payment method
PATCH http://localhost:8000/api/v1/payment-method
Content-Type:application/json

{
  "name": "Pay BY Credit Card",
  "status":"active",
  "description":"Use this payment method to pay by Credit or Debit masterCard"
}